# Generated by Django 5.1.2 on 2024-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "profile_picture_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resume_url", models.CharField(blank=True, max_length=255, null=True)),
                ("job_preferences", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profile",
                "managed": False,
            },
        ),
    ]
