# Generated by Django 5.1.2 on 2025-02-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": True},
        ),
    ]
