# Generated by Django 5.1.2 on 2024-11-15 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": True},
        ),
    ]
