# Generated by Django 5.1.2 on 2024-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0002_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="youremail@email.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_preferences",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
