# Generated by Django 5.1.2 on 2024-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0004_remove_userprofile_userlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
