# Generated by Django 5.1.2 on 2024-11-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0005_alter_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
