# Generated by Django 5.1.2 on 2024-11-20 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0006_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": False},
        ),
    ]
