# Generated by Django 5.1.2 on 2024-12-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("user_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("jobs_applied", models.SmallIntegerField(blank=True, null=True)),
                (
                    "num_of_interviews_landed",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("hours_saved", models.SmallIntegerField(blank=True, null=True)),
                (
                    "total_jobs_available",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("limit_left", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Metrics",
                "db_table": "metrics",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
