# Generated by Django 5.1.2 on 2024-11-19 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metrics",
            options={"managed": False, "verbose_name_plural": "Metrics"},
        ),
    ]
