# Generated by Django 5.1.2 on 2025-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("user_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("jobs_applied", models.SmallIntegerField(blank=True, null=True)),
                (
                    "num_of_interviews_landed",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("hours_saved", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "all_metrics",
                "db_table": "all_metrics",
                "db_table_comment": "All time metrics table",
                "ordering": ["id"],
                "managed": True,
            },
        ),
        migrations.AlterModelTableComment(
            name="metrics",
            table_comment="Current Metrics Table",
        ),
    ]
