# Generated by Django 5.1.2 on 2024-11-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0003_alter_metrics_options"),
        ("preferences", "0006_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="email",
            field=models.ForeignKey(
                default="enter@ymail.com",
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
    ]
