# Generated by Django 5.1.2 on 2024-11-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0005_alter_metrics_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="hours_saved",
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
