# Generated by Django 5.1.2 on 2024-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0006_alter_metrics_hours_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="hours_saved",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
