# Generated by Django 5.1.2 on 2024-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0008_alter_metrics_hours_saved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metrics",
            old_name="total_limits",
            new_name="total_limit_left",
        ),
        migrations.AddField(
            model_name="metrics",
            name="plan",
            field=models.CharField(
                choices=[
                    ("SELECT PLAN", "Select plan"),
                    ("BASIC PLAN", "Basic"),
                    ("PREMIUM PLAN", "Premium"),
                    ("PRO PLAN", "Pro"),
                ],
                default="SELECT PLAN",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="metrics",
            name="total_jobs_available",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metrics",
            name="hours_saved",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
