# Generated by Django 5.1.2 on 2024-11-20 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0011_alter_metrics_email_alter_metrics_hours_saved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metrics",
            options={"managed": False, "verbose_name_plural": "Metrics"},
        ),
    ]
