# Generated by Django 5.1.2 on 2024-11-20 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0012_alter_metrics_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metrics",
            options={"managed": True, "verbose_name_plural": "Metrics"},
        ),
    ]
