# Generated by Django 5.1.2 on 2024-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0014_remove_metrics_total_limit_left_metrics_limit_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="hours_saved",
            field=models.FloatField(),
        ),
    ]
