# Generated by Django 5.1.2 on 2024-11-22 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0017_alter_metrics_email"),
        ("preferences", "0007_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
    ]
