# Generated by Django 5.1.2 on 2024-11-22 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0020_alter_metrics_email"),
        ("preferences", "0007_alter_userprofile_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metrics",
            name="id",
        ),
        migrations.AlterField(
            model_name="metrics",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="hours_saved",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="limit_left",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="total_jobs_available",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
