# Generated by Django 5.1.2 on 2024-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0021_remove_metrics_id_alter_metrics_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELECT PLAN", "Select plan"),
                    ("BASIC PLAN", "Basic"),
                    ("PREMIUM PLAN", "Premium"),
                    ("PRO PLAN", "Pro"),
                ],
                default="SELECT PLAN",
                max_length=15,
                null=True,
            ),
        ),
    ]
