# Generated by Django 5.1.2 on 2024-11-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0022_alter_metrics_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
