# Generated by Django 5.1.2 on 2024-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0023_metrics_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metrics",
            name="email",
        ),
        migrations.AddField(
            model_name="metrics",
            name="user_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metrics",
            name="plan",
            field=models.CharField(blank=True, null=True),
        ),
    ]
