# Generated by Django 5.1.2 on 2024-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0024_remove_metrics_email_metrics_user_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
