# Generated by Django 5.1.2 on 2024-11-29 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0026_alter_metrics_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metrics",
            name="plan",
        ),
    ]
