# Generated by Django 5.1.2 on 2024-12-19 22:54

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_uuid",
                    models.UUIDField(
                        blank=True, help_text="Applicant's User ID.", null=True
                    ),
                ),
                (
                    "company_applied_to",
                    models.CharField(help_text="[required]", max_length=255),
                ),
                (
                    "position_applied",
                    models.CharField(help_text="[required]", max_length=255),
                ),
                ("date_submitted", models.DateField(auto_now_add=True)),
                (
                    "experience_required",
                    models.CharField(help_text="[required]", max_length=50),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                        ],
                        default="applied",
                        help_text="[required]",
                        max_length=12,
                    ),
                ),
                (
                    "shared_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "shared_email_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "job_description_link",
                    models.URLField(help_text="[required]", max_length=255),
                ),
                ("full_job_description", models.TextField(help_text="[required]")),
                (
                    "short_job_description",
                    models.CharField(help_text="[required]", max_length=50),
                ),
                ("job_notes", models.TextField(blank=True, null=True)),
                (
                    "user_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employment_preference",
                    models.CharField(
                        choices=[
                            ("Full time", "Full time"),
                            ("Part time", "Part time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        default="Full time",
                        help_text="[required]",
                        max_length=20,
                    ),
                ),
                (
                    "job_location",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                        ],
                        default="On-site",
                        help_text="[required]",
                        max_length=20,
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        choices=[
                            ("Entry-level", "Entry-level"),
                            ("Mid-level", "Mid-level"),
                            ("Senior-level", "Senior-level"),
                            ("Leadership", "Leadership"),
                        ],
                        default="Entry-level",
                        help_text="[required]",
                        max_length=20,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Email of staff initially responsible for this task.",
                        max_length=255,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="[required]",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.userprofile",
                        to_field="email",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Tracker Information",
                "ordering": ["-date_submitted"],
            },
        ),
    ]
