# Generated by Django 5.1.2 on 2024-11-21 15:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("preferences", "0007_alter_userprofile_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_applied_to", models.CharField(max_length=255)),
                ("position_applied", models.CharField(max_length=255)),
                ("date_submitted", models.DateField(auto_now_add=True)),
                ("experience_required", models.CharField(max_length=50)),
                ("resume_used", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Applied", "Applied"),
                            ("Rejected", "Rejected"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                        ],
                        default="In Progress",
                        max_length=12,
                    ),
                ),
                ("shared_email", models.EmailField(max_length=254)),
                ("sensitive_info", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "job_description_link",
                    models.URLField(
                        help_text="link to job description", max_length=255
                    ),
                ),
                ("full_job_description", models.TextField()),
                ("short_job_description", models.CharField(max_length=50)),
                (
                    "job_notes",
                    models.TextField(blank=True, help_text="(optional)", null=True),
                ),
                ("user_location", models.CharField(max_length=255)),
                (
                    "employment_preference",
                    models.CharField(
                        choices=[
                            ("Full time", "Full time"),
                            ("Part time", "Part time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        default="Full time",
                        max_length=20,
                    ),
                ),
                (
                    "job_location",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Hybrid", "Hybrid"),
                            ("Remote", "Remote"),
                        ],
                        default="On-site",
                        max_length=20,
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        choices=[
                            ("Entry-level", "Entry-level"),
                            ("Mid-level", "Mid-level"),
                            ("Senior-level", "Senior-level"),
                            ("Leadership", "Leadership"),
                        ],
                        default="Entry-level",
                        max_length=20,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        help_text="Enter the Linkedin url of the applicant",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Email of staff initially responsible for this task.",
                        max_length=255,
                    ),
                ),
                ("salary_range", models.CharField()),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Email of applicant",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.userprofile",
                        to_field="email",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Email of staff that updated this task.",
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dep_update",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Tracker Information",
                "ordering": ["-applicant"],
            },
        ),
    ]
