# Generated by Django 5.1.2 on 2024-11-02 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(blank=True, default=uuid.uuid4, null=True),
                ),
                ("email", models.EmailField(max_length=255)),
                ("company_applied_to", models.CharField(max_length=255)),
                ("position_applied", models.CharField(max_length=255)),
                ("date_submitted", models.DateField(auto_now_add=True)),
                ("experience_required", models.CharField(max_length=50)),
                ("resume_used", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("P", "In Progress"),
                            ("A", "Applied"),
                            ("R", "Rejected"),
                            ("I", "Interview"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("job_notes", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Job Tracker Information",
                "ordering": ["-date_submitted"],
            },
        ),
    ]
