# Generated by Django 5.1.2 on 2024-11-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="user_id",
            field=models.UUIDField(blank=True, default="", null=True),
        ),
    ]
