# Generated by Django 5.1.2 on 2024-11-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="salary_range",
            field=models.CharField(max_length=100),
        ),
    ]
