# Generated by Django 5.1.2 on 2024-11-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_jobtracker_salary_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="application_counter",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
