# Generated by Django 5.1.2 on 2025-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="resume_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(help_text="[required]", max_length=255),
        ),
    ]
