# Generated by Django 5.1.2 on 2024-11-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_jobtracker_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
