# Generated by Django 5.1.2 on 2024-11-22 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_jobtracker_application_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="application_counter",
        ),
    ]
