# Generated by Django 5.1.2 on 2025-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_jobtracker_resume_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="date_submitted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
