# Generated by Django 5.1.2 on 2025-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_jobtracker_date_submitted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="date_submitted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
