# Generated by Django 5.1.2 on 2024-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_remove_jobtracker_application_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("rejected", "Rejected"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                ],
                default="applied",
                max_length=12,
            ),
        ),
    ]
