# Generated by Django 5.1.2 on 2024-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_jobtracker_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
