# Generated by Django 5.1.2 on 2025-01-22 11:27

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_jobtracker_date_submitted"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJobMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "shared_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "shared_email_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("resume_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Meta Data",
                "verbose_name_plural": "User Meta Data",
            },
        ),
        migrations.RemoveField(
            model_name="jobtracker",
            name="resume_url",
        ),
        migrations.RemoveField(
            model_name="jobtracker",
            name="shared_email",
        ),
        migrations.RemoveField(
            model_name="jobtracker",
            name="shared_email_password",
        ),
    ]
