# Generated by Django 5.1.2 on 2024-11-05 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_jobtracker_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="email",
            field=models.EmailField(default="abc@def.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Interview", "Interview"),
                ],
                default="In Progress",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
