# Generated by Django 5.1.2 on 2025-01-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_userjobmetadata_remove_jobtracker_resume_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtracker",
            options={
                "managed": True,
                "ordering": ["-date_submitted"],
                "verbose_name_plural": "Job Tracker Information",
            },
        ),
        migrations.AlterModelOptions(
            name="userjobmetadata",
            options={
                "managed": True,
                "verbose_name": "User Meta Data",
                "verbose_name_plural": "User Meta Data",
            },
        ),
    ]
