# Generated by Django 5.1.2 on 2024-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_jobtracker_applicant_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
