# Generated by Django 5.1.2 on 2024-11-06 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0007_alter_jobtracker_options_remove_jobtracker_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="created_by",
            field=models.ForeignKey(
                default="staff",
                help_text="Name of staff initially responsible for this task.",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dep_create",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="updated_by",
            field=models.ForeignKey(
                default="staff",
                help_text="Name of staff that updated this task.",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dep_update",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
            preserve_default=False,
        ),
    ]
