# Generated by Django 5.1.2 on 2025-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_alter_jobtracker_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjobmetadata",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
