# Generated by Django 5.1.2 on 2024-11-06 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_jobtracker_created_by_jobtracker_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtracker",
            options={
                "ordering": ["-applicant"],
                "verbose_name_plural": "Job Tracker Information",
            },
        ),
        migrations.RemoveField(
            model_name="jobtracker",
            name="user",
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="applicant",
            field=models.ForeignKey(
                default="abc@def.com",
                help_text="Email(ID) of applicant",
                limit_choices_to={"is_staff": False},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="created_by",
            field=models.ForeignKey(
                help_text="Email of staff initially responsible for this task.",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dep_create",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Email of staff that updated this task.",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dep_update",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
