# Generated by Django 5.1.2 on 2025-01-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_alter_userjobmetadata_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjobmetadata",
            name="shared_email_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
