# Generated by Django 5.1.2 on 2024-11-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_alter_jobtracker_options_remove_jobtracker_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="applicant_name",
            field=models.CharField(
                default="Jane Doe", help_text="Fullname of applicant", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant",
            field=models.ForeignKey(
                help_text="Email (ID) of applicant",
                limit_choices_to={"is_staff": False},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
