# Generated by Django 5.1.2 on 2025-01-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
        ("tracker", "0009_alter_userjobmetadata_shared_email_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjobmetadata",
            name="user_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
    ]
