# Generated by Django 5.1.2 on 2025-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_alter_userjobmetadata_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userjobmetadata",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
