# Generated by Django 5.1.2 on 2024-11-10 00:26

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_jobtracker_applicant_name_alter_jobtracker_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="job_description_link",
            field=models.URLField(
                default="kirro.ai", help_text="link to job description", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="sensitive_info",
            field=encrypted_model_fields.fields.EncryptedCharField(default="psw"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="shared_email",
            field=models.EmailField(default="shared_email@ymail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="job_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
