# Generated by Django 5.1.2 on 2024-11-28 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_alter_jobtracker_applicant_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.UUIDField(
                default=uuid.UUID("e9c03432-23c9-4bb0-afa3-b31e5572c90a")
            ),
        ),
    ]
