# Generated by Django 5.1.2 on 2025-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_alter_userjobmetadata_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="no_of_interviews_landed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="no_of_jobs_applied",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
