# Generated by Django 5.1.2 on 2025-02-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_jobtracker_no_of_interviews_landed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="date_submitted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
