# Generated by Django 5.1.2 on 2024-11-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0007_alter_userprofile_options"),
        ("tracker", "0013_alter_jobtracker_applicant_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_guid",
                to="preferences.userprofile",
            ),
        ),
    ]
