# Generated by Django 5.1.2 on 2025-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_jobtracker_date_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjobmetadata",
            name="preferences_complete",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
