# Generated by Django 5.1.2 on 2024-11-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0007_alter_userprofile_options"),
        ("tracker", "0014_alter_jobtracker_applicant_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="applicant_uuid",
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="applicant_guid",
                to="preferences.userprofile",
            ),
        ),
    ]
