# Generated by Django 5.1.2 on 2024-11-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0014_alter_jobtracker_application_counter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="application_counter",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
