# Generated by Django 5.1.2 on 2025-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_userjobmetadata_preferences_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="offer_letter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="resume_used",
            field=models.URLField(blank=True, null=True),
        ),
    ]
