# Generated by Django 5.1.2 on 2024-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0015_alter_jobtracker_application_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="job_preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
