# Generated by Django 5.1.2 on 2024-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0016_alter_jobtracker_job_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="job_preferences",
            field=models.URLField(default="http://127.0.0.1:8000/trackers/"),
        ),
    ]
