# Generated by Django 5.1.2 on 2024-11-15 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0018_alter_jobtracker_job_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="job_preferences",
        ),
    ]
