# Generated by Django 5.1.2 on 2024-12-08 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0007_alter_userprofile_options"),
        ("tracker", "0018_remove_jobtracker_resume_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant",
            field=models.ForeignKey(
                help_text="[required]",
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("rejected", "Rejected"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                ],
                default="applied",
                help_text="[required]",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="company_applied_to",
            field=models.CharField(help_text="[required]", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="employment_preference",
            field=models.CharField(
                choices=[
                    ("Full time", "Full time"),
                    ("Part time", "Part time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                ],
                default="Full time",
                help_text="[required]",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="experience_required",
            field=models.CharField(help_text="[required]", max_length=50),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="full_job_description",
            field=models.TextField(help_text="[required]"),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="job_description_link",
            field=models.URLField(help_text="[required]", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="job_level",
            field=models.CharField(
                choices=[
                    ("Entry-level", "Entry-level"),
                    ("Mid-level", "Mid-level"),
                    ("Senior-level", "Senior-level"),
                    ("Leadership", "Leadership"),
                ],
                default="Entry-level",
                help_text="[required]",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="job_location",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                ],
                default="On-site",
                help_text="[required]",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="position_applied",
            field=models.CharField(help_text="[required]", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(help_text="[required]", max_length=50),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="updated_by",
            field=models.ForeignKey(
                help_text="[required]",
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dep_update",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
