# Generated by Django 5.1.2 on 2024-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0019_alter_jobtracker_applicant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant_uuid",
            field=models.UUIDField(
                blank=True, help_text="Applicant's User ID.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="user_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
