# Generated by Django 5.1.2 on 2024-11-15 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
        ("tracker", "0020_alter_jobtracker_applicant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="application_counter",
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="applicant",
            field=models.ForeignKey(
                help_text="Email (ID) of applicant",
                on_delete=django.db.models.deletion.CASCADE,
                to="preferences.userprofile",
                to_field="email",
            ),
        ),
    ]
