# Generated by Django 5.1.2 on 2024-12-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0020_alter_jobtracker_applicant_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtracker",
            options={
                "ordering": ["-date_submitted"],
                "verbose_name_plural": "Job Tracker Information",
            },
        ),
        migrations.RenameField(
            model_name="jobtracker",
            old_name="sensitive_info",
            new_name="shared_email_password",
        ),
    ]
