# Generated by Django 5.1.2 on 2024-11-16 12:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0022_alter_jobtracker_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="full_job_description",
            field=models.TextField(default="full job description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(
                default="short job description",
                verbose_name=django.db.models.functions.text.Substr(
                    "full_job_description", 1, 50
                ),
            ),
            preserve_default=False,
        ),
    ]
