# Generated by Django 5.1.2 on 2024-11-16 12:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0023_jobtracker_full_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(
                editable=False,
                verbose_name=django.db.models.functions.text.Substr(
                    "full_job_description", 1, 50
                ),
            ),
        ),
    ]
