# Generated by Django 5.1.2 on 2024-11-16 12:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0024_alter_jobtracker_short_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(
                default=django.db.models.functions.text.Substr(
                    "full_job_description", 1, 50
                ),
                editable=False,
            ),
        ),
    ]
