# Generated by Django 5.1.2 on 2024-11-16 12:43

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0025_alter_jobtracker_short_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(
            ),
        ),
    ]
