# Generated by Django 5.1.2 on 2024-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0027_alter_jobtracker_short_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtracker",
            name="job_notes",
            field=models.TextField(blank=True, help_text="(optional)", null=True),
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="short_job_description",
            field=models.CharField(max_length=50),
        ),
    ]
