# Generated by Django 5.1.2 on 2024-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0028_alter_jobtracker_job_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtracker",
            name="applicant_name",
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="employment_preference",
            field=models.CharField(
                choices=[
                    ("Full time", "Full time"),
                    ("Part time", "Part time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                ],
                default="Full time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="job_level",
            field=models.CharField(
                choices=[
                    ("Entry-level", "Entry-level"),
                    ("Mid-level", "Mid-level"),
                    ("Senior-level", "Senior-level"),
                    ("Leadership", "Leadership"),
                ],
                default="Entry-level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="job_location",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                ],
                default="On-site",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="linkedin_url",
            field=models.URLField(
                default="linkedin.com",
                help_text="Enter the Linkedin url of the applicant",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="user_location",
            field=models.CharField(default="remote", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobtracker",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Interview", "Interview"),
                    ("Offer", "Offer"),
                ],
                default="In Progress",
                max_length=12,
            ),
        ),
    ]
