# Generated by Django 5.1.2 on 2024-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0029_remove_jobtracker_applicant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtracker",
            name="counter",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
