# Generated by Django 5.1.2 on 2024-11-20 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0030_jobtracker_counter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobtracker",
            old_name="counter",
            new_name="ret_counter",
        ),
    ]
